### PR TITLE
implement loading progress 

### PR DESCRIPTION
**Pull request by tomsean**
screenshot_2015-08-09-12-26-16

loading progress just add 
"browserProgress": {
                "showProgress": true,
                "progressBgColor": "#016585",
                "progressColor": "#FFAA16"
            }
to option config
but,now just implement android and ios platform.

### CODE REVIEW

**Comment by powowbox** [comment]
tested on ios 7.1 (iphone 4S), ios9.2 iphone 6S
android 4.2, gtab3

works great

**Comment by dorraba** [comment]
I am using this plugin in Phonegap build via npm, the loading bar is not showing altough I used the code above

**Comment by ramshengale** [comment]
Hey.. I'm looking forward to seeing this added to the plugin. Do you have any plans for the same?

**Comment by ricolo** [comment]
@tomsean Thanks for adding this feature. It works great on android platform, but on iOS it shows an animated spinner instead of progress bar at the top even with the same option config as you mentioned above. Both iOS version 9.1 and 9.2 show the same issue. Here's the spinner in iOS:

spinner in iOS

**Comment by ricolo** [comment]
@tomsean Besides, even I set `"showProgress": false` I can't turn off the spinner in iOS.

**Comment by ramshengale** [comment]
@ricolo How are you able to use this feature in your app? I see no showProgress or browserProgress code in my local copy of this plugin. Also I searched in the code on https://github.com/initialxy/cordova-plugin-themeablebrowser/ I don't see the changes there as suggested in this Pull.

Sorry if I missed something. I'm new to github and don't know how to use the updated code done in this pull.

**Comment by ricolo** [comment]
@ramshengale I git clone the develop branch of [tomsean's fork](https://github.com/tomsean/cordova-plugin-themeablebrowser) to local directory, and add the cordova plugin from there. I don't know how long I will have to wait for the merge so I have to resort to this rather manual approach (I would like to know if there's a better way to do it too).

**Comment by ramshengale** [comment]
@ricolo If the git version that you're using is working fine (at least for Android and spinner for ios) I think @initialxy can merge this pull to the main plugin. 

P.S. - For your issue of spinner on ios, sorry can't help with that, not an ios dev. :-(

**Comment by ricolo** [comment]
@tomsean Sorry just found out that the iOS implementation is only included in `dev` branch instead of `develop` branch of your fork, so it works in iOS now.

**Comment by Neotrixsx** [comment]
@tomsean I am a little bit confuse please help me in which place I put your code in my app.

**Comment by tomsean** [comment]
@Neotrixsx yes,you just add this plugin to you cordova project and then readd android or ios platform.
then write you js code in you app

**Comment by Neotrixsx** [comment]
I did every think. but i don't know where i put 

"browserProgress": {
"showProgress": true,
"progressBgColor": "#016585",
"progressColor": "#FFAA16"
}

code in my app.
 above you said "put to option config" i am little bit confuse.

**Comment by chaitanyagupta76** [comment]
couldn't get this feature in current version of plugin. Please help.

**Comment by Malkiat-Singh** [comment]
same here not working with 0.2.17 version

**Pull request closed without merging**
